# Generated by Django 2.2 on 2020-06-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stackoverflow_link', models.URLField(blank=True, max_length=1000)),
                ('codechef_link', models.URLField(blank=True, max_length=1000)),
                ('codeforces_link', models.URLField(blank=True, max_length=1000)),
                ('stackoverflow_points', models.CharField(blank=True, max_length=200)),
                ('codechef_points', models.CharField(blank=True, max_length=200)),
                ('codeforces_points', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.FileField(upload_to='uploadimages/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
