# Generated by Django 2.2 on 2020-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='message_toC',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='techgig_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
