# Generated by Django 2.2 on 2020-06-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20200610_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.CharField(blank=True, max_length=200)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
