# Generated by Django 2.2 on 2020-06-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0005_contactdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='user_name',
            new_name='user_name11',
        ),
    ]
