# Generated by Django 2.2 on 2020-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0007_auto_20200611_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile1',
            name='codechef_points',
            field=models.CharField(blank=True, default='00', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile1',
            name='codeforces_points',
            field=models.CharField(blank=True, default='00', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile1',
            name='stackoverflow_points',
            field=models.CharField(blank=True, default='00', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile1',
            name='techgig_points',
            field=models.CharField(blank=True, default='00', max_length=200),
        ),
    ]
